[build-system]
requires = ["maturin>=1.0,<2.0", "polars>=1.3.0"]
build-backend = "maturin"

[project]
name = "polars-reverse-geocode"
requires-python = ">=3.10"
readme = "README.md"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/MarcoGorelli/polars-reverse-geocode"
Issues = "https://github.com/MarcoGorelli/polars-reverse-geocode/issues"

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",
    "D203",
    "D213",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "D",
    "S", # Allow asserts, subprocess usage.
]
"t.py" = [
    "T201", # Allow print.
]
"bump_version.py" = [
    "ALL",
]
